### ISSUE TITLE
Craft 4 Unexpected token "name" of value "if" ("end of statement block" expected).

### ISSUE THREAD

**Issue by daafbleumink** [c10d-dev/craft-recaptcha#1]
Hi there,

When I update my Craft environment to version 4 an error message appears.
Are there any of you out there experiencing this same error?

You can find the whole error message here and a screenshot attached:

`Twig\Error\SyntaxError: Unexpected token "name" of value "if" ("end of statement block" expected). in /Users/daafbleumink/Sites/tewelscher/vendor/c10d/craft-recaptcha/src/templates/_bind-button.twig:15
Stack trace:
#0 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/TokenParser/ForTokenParser.php(41): Twig\TokenStream->expect(3)
#1 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Parser.php(170): Twig\TokenParser\ForTokenParser->parse(Object(Twig\Token))
#2 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/TokenParser/IfTokenParser.php(41): Twig\Parser->subparse(Array)
#3 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Parser.php(170): Twig\TokenParser\IfTokenParser->parse(Object(Twig\Token))
#4 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Parser.php(83): Twig\Parser->subparse(NULL, false)
#5 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(488): Twig\Parser->parse(Object(Twig\TokenStream))
#6 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(516): Twig\Environment->parse(Object(Twig\TokenStream))
#7 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/twig/Environment.php(39): Twig\Environment->compileSource(Object(Twig\Source))
#8 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(348): craft\web\twig\Environment->compileSource(Object(Twig\Source))
#9 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'craft-recaptcha...')
#10 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('craft-recaptcha...')
#11 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render('craft-recaptcha...', Array)
#12 /Users/daafbleumink/Sites/tewelscher/vendor/c10d/craft-recaptcha/src/services/RecaptchaService.php(57): craft\web\View->renderTemplate('craft-recaptcha...', Array, 'cp')
#13 /Users/daafbleumink/Sites/tewelscher/vendor/c10d/craft-recaptcha/src/services/RecaptchaService.php(64): c10d\craftrecaptcha\services\RecaptchaService->render('recaptcha-1', Array, 'craft-recaptcha...')
#14 /Users/daafbleumink/Sites/tewelscher/vendor/c10d/craft-recaptcha/src/variables/RecaptchaVariable.php(47): c10d\craftrecaptcha\services\RecaptchaService->renderBindButton('submit-contact-...', 'recaptcha-1', Array)
#15 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Extension/CoreExtension.php(1607): c10d\craftrecaptcha\variables\RecaptchaVariable->renderBindButton('submit-contact-...')
#16 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/helpers/Template.php(101): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(c10d\craftrecaptcha\variables\RecaptchaVariable), 'renderBindButto...', Array, 'method', false, false)
#17 /Users/daafbleumink/Sites/tewelscher/storage/runtime/compiled_templates/da/da3120d539717dfae6b4ab5529910013.php(144): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(c10d\craftrecaptcha\variables\RecaptchaVariable), 'renderBindButto...', Array, 'method')
#18 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e2ce5e1d555d7b364fb8097a801670a5->doDisplay(Array, Array)
#19 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/daafbleumink/Sites/tewelscher/storage/runtime/compiled_templates/b9/b94de9a8cf8e8f561f1ba70e48c6403e.php(95): Twig\Template->display(Array)
#21 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(171): __TwigTemplate_9439cb0b44b5c0b038d771ac3494563a->block_content(Array, Array)
#22 /Users/daafbleumink/Sites/tewelscher/storage/runtime/compiled_templates/61/612b622f76a8b53c8b5cbe6a7e1335f6.php(99): Twig\Template->displayBlock('content', Array, Array)
#23 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d51ccd890ab57a46e1421d6b890191d3->doDisplay(Array, Array)
#24 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/daafbleumink/Sites/tewelscher/storage/runtime/compiled_templates/b9/b94de9a8cf8e8f561f1ba70e48c6403e.php(50): Twig\Template->display(Array, Array)
#26 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9439cb0b44b5c0b038d771ac3494563a->doDisplay(Array, Array)
#27 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#29 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#30 /Users/daafbleumink/Sites/tewelscher/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#31 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render('contact.twig', Array)
#32 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/View.php(481): craft\web\View->renderTemplate('contact.twig', Array)
#33 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('contact.twig', Array, 'site')
#34 /Users/daafbleumink/Sites/tewelscher/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#35 /Users/daafbleumink/Sites/tewelscher/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#36 /Users/daafbleumink/Sites/tewelscher/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#37 /Users/daafbleumink/Sites/tewelscher/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#38 /Users/daafbleumink/Sites/tewelscher/web/index.php(12): yii\base\Application->run()
#39 /Users/daafbleumink/.composer/vendor/laravel/valet/server.php(234): require('/Users/daafbleu...')
#40 {main}
`

![Screenshot 2022-07-14 at 17 07 26](https://user-images.githubusercontent.com/29104452/179015303-d8ad4ff2-c414-4df8-a044-c5c3865e1299.png)

Kind regards,

Daaf

**Comment by c10d-dev** [comment]
Hello,
Thank you for reporting this!!

It seems that since Twig 2.10, `for ... if` is not working anymore.
> As of Twig 2.10, use the [filter](https://twig.symfony.com/doc/2.x/filters/filter.html) filter instead, or an if condition inside the for body (if your condition depends on a variable updated inside the loop and you are not using the loop variable).

I'll push a new version, let me know if it fixes the bug on your end.
Thanks!

**Comment by daafbleumink** [comment]
Yes it's fixed now. Thanks for the quick response!
