### ISSUE TITLE
Allow native HTML form validation on user registration forms

### ISSUE THREAD

**Issue by mijewe** [c10d-dev/craft-recaptcha#2]
Because the Recaptcha must be added using `renderBindButton`, which then submits the form with JS on the `recaptchaBeforeSubmit` callback, native HTML form validation is skipped.

I believe this can be achieved with something like

```
const form = document.getElementById("{{ options.button }}").closest("form");
if (form.reportValidity()) {
	form.submit();
}
```

**Comment by c10d-dev** [comment]
Hello,
Thanks for this comment!

First, you don't have to use the `renderSubmitButton` or `renderBindButton` functions provided by the plugin, you can recreate the whole recaptcha setup by yourself in your templates.

However, I understand your point, and I'll check to integrate your solution in the coming weeks!

**Comment by c10d-dev** [comment]
Hello @mijewe!

It should work now on the v2.1.0, could you try and test it?

Thanks!
