### ISSUE TITLE
Supporting automated testing

### ISSUE THREAD

**Issue by sparkalow** [c10d-dev/craft-recaptcha#5]
Is there a way to disable reCatpcha checks for local automated testing with say cypress.io?  Being able to set the threshold in an ENV variable or config file would suffice.

**Comment by c10d-dev** [comment]
Hello, the threshold could be set in the php Config file, so I guess this could work!
However, I could add an env var to disable the check entirely in a next release.

**Comment by sparkalow** [comment]
I missed that config setting. Sounds like it would work.  An env var would probably be helpful though.

**Comment by c10d-dev** [comment]
The new v2.2.0 release is out!
This one adds an environment variable "CRAFT_RECAPTCHA_SKIP_VERIFICATION" to be able to skip the verification in your CI pipeline!
