### ISSUE TITLE
Settings keys as environment variables doesn't work

### ISSUE THREAD

**Issue by fdelaneau** [c10d-dev/craft-recaptcha#7]
I have a defined both my site key and secret key in my `.env` and called the variables in the plugin's preferences.
The interface did auto-complete the names so I was convinced it would work.

In the template, I binded my submit button :

```
{{ craft.recaptcha.renderBindButton('submit') }}
<button id="submit">Envoyer</button>
```

When reviewing the generated HTML, the plugin does work and modified the button but the `data-sitekey` is empty :(

```
<button id="submit" class="g-recaptcha" data-callback="recaptchaBeforeSubmit" data-action="submit" data-sitekey="" type="submit">Envoyer</button>
```

EDIT
Found the source of the problem on my side, sorry for the spam.

**Comment by c10d-dev** [comment]
No problem!
For my info, what was the issue/solution and what is your Craft version ?

**Comment by fdelaneau** [comment]
Pure user error, nothing on your side. 

My issue was simply a bad copy-paste. As I was updating several craft sites and added your plugin, I didn't notice that my button id was not the always exactly the same.
