### ISSUE TITLE
Multiple forms in a single page

### ISSUE THREAD

**Issue by pnpaes** [c10d-dev/craft-recaptcha#8]
Hi, it seems that if I have multiple forms in a single page the plugin is not able to handle it.
It creates multiple of the recaptchaBeforeSubmit functions, but since they are all on the "window" level, one the last one will run as it overwrites the others.
Maybe a solution would be to move the function inside each "DOMContentLoaded" generate for each implementation, that way they are not global nor cross accessible.

**Comment by pnpaes** [comment]
Ok, I forked it here and made an implementation that supports multiple forms int he same page.
I added a property to the [options] parameter. when that property is present it appends something to the callback function, so I can have multiple callback functions instead of just one. that was a quick fix. ideally I should add the form as a reference to the button. so when the button is clicked, the callback would fetch the form from the button and the use that one to define which form to submit.
i will try to play a bit when I have more time and see if I can make a solution that is so "shady". if I manage to do it I will create a pull request ;)

**Comment by c10d-dev** [comment]
Hello there!
I'm glad you found a way but I think you could have used the `.render()` function with a different id for each form and possibly a custom template too!
Best regards

**Comment by Siyabulela** [comment]
This is also not working for me. I have two forms in 1 page. When I click 'submit' on the first form, it forces me to fill the last form so that it can submit

```twig
{{ craft.recaptcha.renderBindButton('submit-' ~ formConfigEntry.id) }}
<button type="submit" class="btn btn-primary" id="submit-{{ formConfigEntry.id }}">
  <span data-submitting-text class="hide"><i class="fa fa-spinner fa-pulse"></i> {{ 'Submitting' | t }}</span>
  <span data-submit-text>{{ submitButtonText | t }}</span>
</button>
```
